/**
 * The durable offline capture queue.
 *
 * A field rep captures with no signal, the app is force-quit, and the captures
 * must still be there on restart. That single requirement is what makes this a
 * PERSISTED queue rather than an array in a React state hook — a hook loses
 * everything the moment the process dies, which is exactly the moment this
 * exists for.
 *
 * Storage is injected rather than reaching for `window.localStorage` directly,
 * so the queue can be tested without a DOM and so a mobile shell can swap in a
 * device-appropriate store without this logic changing.
 */

/** The subset of the Web Storage API this queue needs. */
export interface QueueStorage {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

/** Where an item is in its journey to the server. */
export type SyncState =
  /** Captured, never sent. */
  | 'pending'
  /** Sent, no answer yet. The state a force-quit interrupts. */
  | 'in_flight'
  /** The server confirmed it. Safe to drop. */
  | 'synced'
  /** The server refused it for a reason retrying will not fix. */
  | 'rejected';

export interface QueueItem {
  /** Minted HERE, on the device, at capture time. The idempotency key. */
  clientCaptureId: string;
  captureKind: 'contact' | 'business_card' | 'voice_note';
  rawInput: string;
  originClass: string;
  propertyReference: string | null;
  /** When the DEVICE took it. */
  capturedAt: string;
  syncState: SyncState;
  /** How many times sync has been attempted, for backoff and for triage. */
  attempts: number;
  /** Set when the server rejected it, so the operator can be told why. */
  error: string | null;
}

const STORAGE_KEY = 'leadflow.captureQueue.v1';

/**
 * Read the queue.
 *
 * A CORRUPT STORE RETURNS EMPTY RATHER THAN THROWING. If the JSON will not
 * parse there is nothing to recover, and throwing here would take down the app
 * on launch — the operator would lose the queue AND the product. Losing the
 * queue is bad; being unable to open the app to find that out is worse.
 */
export function readQueue(storage: QueueStorage): QueueItem[] {
  try {
    const raw = storage.getItem(STORAGE_KEY);
    if (!raw) {
      return [];
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as QueueItem[]) : [];
  } catch {
    return [];
  }
}

/** Persist the queue. */
export function writeQueue(storage: QueueStorage, items: QueueItem[]): void {
  storage.setItem(STORAGE_KEY, JSON.stringify(items));
}

/**
 * Add a capture to the queue.
 *
 * The id is generated by the CALLER and passed in, so a capture taken with no
 * signal already carries the identity the server will later deduplicate on.
 * Generating it at send time instead would defeat the entire design: two sends
 * of the same capture would carry two ids and become two records.
 */
export function enqueue(
  storage: QueueStorage,
  item: Omit<QueueItem, 'syncState' | 'attempts' | 'error'>
): QueueItem[] {
  const queue = readQueue(storage);
  // Idempotent on the device too. A double-tap on Save must not queue twice.
  if (queue.some((existing) => existing.clientCaptureId === item.clientCaptureId)) {
    return queue;
  }
  const next = [...queue, { ...item, syncState: 'pending' as const, attempts: 0, error: null }];
  writeQueue(storage, next);
  return next;
}

/**
 * What to send on the next sync.
 *
 * INCLUDES `in_flight`, and that is the crucial part. An item marked in-flight
 * when the app was force-quit received no answer — it may have landed or it may
 * not, and the device cannot tell. Excluding it would silently lose a capture
 * that never arrived; including it is safe precisely because the server
 * deduplicates on the client id. The whole design leans on that: the client
 * retries whatever it is unsure about, and the server decides what is new.
 */
export function itemsToSync(queue: QueueItem[]): QueueItem[] {
  return queue.filter((item) => item.syncState === 'pending' || item.syncState === 'in_flight');
}

/** Mark items as sent, before the request goes out. */
export function markInFlight(storage: QueueStorage, ids: string[]): QueueItem[] {
  const next = readQueue(storage).map((item) =>
    ids.includes(item.clientCaptureId)
      ? { ...item, syncState: 'in_flight' as const, attempts: item.attempts + 1 }
      : item
  );
  writeQueue(storage, next);
  return next;
}

/**
 * Apply the server's per-item verdicts.
 *
 * A DUPLICATE COUNTS AS SYNCED. The server is telling us this capture already
 * exists — which is success, not failure. Treating it as an error would leave
 * the item in the queue forever, retried on every sync, and the Offline Queue
 * count would never reach zero for a rep who did nothing wrong.
 */
export function applyOutcomes(
  storage: QueueStorage,
  outcomes: { clientCaptureId: string; status: string; error?: string | null }[]
): QueueItem[] {
  const byId = new Map(outcomes.map((outcome) => [outcome.clientCaptureId, outcome]));

  const next = readQueue(storage).map((item) => {
    const outcome = byId.get(item.clientCaptureId);
    if (!outcome) {
      return item;
    }
    if (outcome.status === 'accepted' || outcome.status === 'duplicate') {
      return { ...item, syncState: 'synced' as const, error: null };
    }
    // Back to pending, not rejected: a failure here is usually the network, and
    // the item must be tried again. Only a server refusal the client can read
    // as permanent should stop it retrying.
    return { ...item, syncState: 'pending' as const, error: outcome.error ?? 'Sync failed' };
  });

  writeQueue(storage, next);
  return next;
}

/** Drop everything the server has confirmed. */
export function purgeSynced(storage: QueueStorage): QueueItem[] {
  const next = readQueue(storage).filter((item) => item.syncState !== 'synced');
  writeQueue(storage, next);
  return next;
}

/**
 * The number shown in the Capture Inbox.
 *
 * Counts what is still OWED to the server — pending and in-flight. Synced items
 * are not outstanding work, and including them would show a rep a backlog they
 * have already cleared.
 */
export function outstandingCount(queue: QueueItem[]): number {
  return queue.filter((item) => item.syncState === 'pending' || item.syncState === 'in_flight')
    .length;
}
